name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract version from tag
      id: get_version
      run: |
        # Remove 'v' prefix and '-test' suffix
        TAG=${GITHUB_REF#refs/tags/v}
        VERSION=${TAG%-test}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build distribution
      run: python setup.py sdist bdist_wheel
      env:
        PACKAGE_VERSION: ${{ env.VERSION }}

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
